on: workflow_dispatch
name: Deploy Azure Resource Manager (ARM) Template
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      # Log into Azure
    - uses: actions/checkout@master
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy ARM Template
    - name: deploy
      uses: Azure/arm-deploy@v1.0.9
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: "./Resources/ARM-Templates/container-webapp-template.json"
        failOnStdErr: false
